### ISSUE TITLE
Error when adding GeyserMC via Hangar

### ISSUE THREAD

**Issue by Baumx1234** [Phoenix616/Updater#6]
### What is happening?

I want to add GeyserMC via Hangar, but I get an error.

### What did you expect to happen?

I was expecting the plugin to be downloaded.

### Version

Build 52

### Config

```YAML
WorldEdit {
	source = bukkit
	placeholders {
		pluginid=31043
	}
}
ViaVersion {
	source=github
	placeholders {
		user=ViaVersion
		repository=ViaVersion
	}
}
HeadDB {
	source=github
	placeholders {
		user=TheSilentPro
		repository=HeadDB
	}
}
Geyser{
	source = hangar
	placeholders{
		user=GeyserMC
		project=Geyser
	}
}
```

### Server/system Version

Debian (12) 6.1.85-1 (2024-04-11) x86_64 GNU/Linux

### Log

```shell
E:\Users\Daniel\Desktop\MCSERVER>java -jar PhoenixUpdater.jar -t plugins
PhoenixUpdater 1.2-SNAPSHOT (build 52)
Copyright (C) 2020 Max Lee aka Phoenix616 (max@themoep.de)
    By using this program you agree to the terms of the AGPLv3
    The full license text can be found here: https://phoenix616.dev/licenses/agpl-v3.txt
    This program's source is available here: https://github.com/Phoenix616/Updater
[INFO] Found new version of WorldEdit on BUKKIT: WorldEdit 7.3.0 (Bukkit for 1.20+)
[INFO] Downloading WorldEdit WorldEdit 7.3.0 (Bukkit for 1.20+)...
[INFO] Done!
[INFO] Successfully downloaded plugin jar file!
[INFO] Linked plugins\WorldEdit.jar to plugins\WorldEdit.jar-WorldEdit
[INFO] Found new version of Geyser on HANGAR: Geyser
[INFO] Downloading Geyser Geyser...
Exception in thread "main" java.lang.ClassCastException: class com.google.gson.JsonNull cannot be cast to class com.google.gson.JsonObject (com.google.gson.JsonNull and com.google.gson.JsonObject are in unnamed module of loader 'app')
        at com.google.gson.JsonObject.getAsJsonObject(JsonObject.java:221)
        at dev.phoenix616.updater.sources.HangarSource.getMd5Hash(HangarSource.java:113)
        at dev.phoenix616.updater.sources.HangarSource.downloadUpdate(HangarSource.java:175)
        at dev.phoenix616.updater.Updater.check(Updater.java:347)
        at dev.phoenix616.updater.Updater.check(Updater.java:335)
        at dev.phoenix616.updater.Updater.run(Updater.java:255)
        at dev.phoenix616.updater.application.Main.main(Main.java:97)
```

### What other programs/plugins are you running?

HeadDB
WorldEdit
ViaVersion

**Comment by Phoenix616** [comment]
Hangar should work these days (at least I'm updating plugins from there). If you still have issues with it please open a new issue with a new log using the current version.
